name: Build and publish image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.PUBLISH_USER }}
          password: ${{ secrets.PUBLISH_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/murphnomer/nodejs-docker:latest
            ghcr.io/murphnomer/nodejs-docker:${{ github.sha }}
